@baseUrl = http://localhost:3140/api
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Otávio Monteiro Rossoni",
  "email": "otarossoni@gmail.com",
  "password": "123456" 
}

###

# @name authenticate
POST {{baseUrl}}/session
Content-Type: application/json

{
  "email": "otarossoni@gmail.com",
  "password": "123456" 
}

###

# @name create_philosophy_school
POST {{baseUrl}}/school
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Cartesianismo",
  "century": "XVII e XVIII d.C."
}

###

# @name create_philosopher
POST {{baseUrl}}/philosopher
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "René Descartes",
  "nationality": "Francês",
  "born_date": "1596-03-31T00:00:00Z B.C.",
  "death_date": "1650-02-11T00:00:00Z B.C.",
  "school_id": "2016d224-c038-45c0-b3ca-96803db5ada7"
}
  
###

# @name link_philosopher_to_philosophy_school
POST {{baseUrl}}/philosopher/link
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "philosopher_id": "8b23067c-cbf6-4a5a-9b40-fa93d03e4095",
  "school_id": "13a8f966-bcac-4b31-8e8e-0142cc45d173"
}
  
###

# @name create_quote
POST {{baseUrl}}/quote
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "philosopher_id": "8b23067c-cbf6-4a5a-9b40-fa93d03e4095",
  "phrase": "I think, therefore I Am"
}
  
###

# @name create_quote_list
POST {{baseUrl}}/quote/list
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "philosopher_id": "8b23067c-cbf6-4a5a-9b40-fa93d03e4095",
  "phrases": ["I think, therefore I Am", "The greatest minds are capable of the greatest vices as well as of the greatest virtues."]
}
  
###