@baseUrl = http://localhost:3140/api
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Otávio Monteiro Rossoni",
  "email": "otarossoni@gmail.com",
  "password": "123456" 
}

###

# @name authenticate
POST {{baseUrl}}/session
Content-Type: application/json

{
  "email": "otarossoni@gmail.com",
  "password": "123456" 
}

###

# @name create_philosophy_school
POST {{baseUrl}}/school
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Filosofia Grega Pré-Socrática",
  "century": "V a.C."
}

###

# @name create_philosopher
POST {{baseUrl}}/philosopher
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Sócrates",
  "nationality": "Ateniense",
  "born_date": "0470-01-01T00:00:00Z A.C.",
  "death_date": "0399-01-01T00:00:00Z A.C.",
  "school_id": "577be6f0-2f78-4baa-8938-864ac3f0828f"
}
  
###