@baseUrl = http://localhost:3140/api

# @name create_philosophy_school
POST {{baseUrl}}/school
Content-Type: application/json

{
  "name": "Filosofia Grega Pré-Socrática",
  "century": "V a.C."
}

###